/* Generated by S-function Builder */
#ifndef _SUMBUSSES_BUS_H_
#define _SUMBUSSES_BUS_H_
/* Read only - STARTS */
#ifdef MATLAB_MEX_FILE
#include "tmwtypes.h"
#else
#include "rtwtypes.h"
#endif




#ifndef _DEFINED_TYPEDEF_FOR_Bus1_
#define _DEFINED_TYPEDEF_FOR_Bus1_ 
typedef struct {
  real_T num1;
  real_T num2;
} Bus1;
#endif


#ifndef _DEFINED_TYPEDEF_FOR_Bus2_
#define _DEFINED_TYPEDEF_FOR_Bus2_ 
typedef struct {
  real_T num1;
  real_T num2;
  real_T num3;
} Bus2;
#endif

/* Read only - ENDS */


#endif
